title: Just the Docs Test
description: A test page for Just the Docs
remote_theme: just-the-docs/just-the-docs@v0.7.0
theme: just-the-docs

url: https://matejprasek.github.io/just-the-docs-test/

# logo: "images/sdl.png"
favicon_ico: "/images/favicon.ico"

color_scheme: dark

